### ISSUE TITLE
The tooltip is getting chopped off on top and also on the left corners.

### ISSUE THREAD

**Issue by vidhyavathi** [Caged/d3-tip#139] opened 2015-11-24 06:08 UTC
If I hover on the bar that are in the left corner or top most in the chart, then the tooltip is getting chopped off. Below is the plunker link to show the same.
http://plnkr.co/edit/8uje03DHw16gXwcKVN0o?p=preview
Is there a workaround for now?

**Comment by Caged** [comment] 2016-08-24 15:07
Duplicate of #153

**Closed by Caged** 2016-08-24 15:07 UTC
