### ISSUE TITLE
mouseover on element is not fired if there is a tip hidden on that position

### ISSUE THREAD

**Issue by julbuel** [Caged/d3-tip#108] opened 2015-04-09 13:41 UTC
changing the way you show or hide your tooltip from opacity (0 or 1) to display (block or none)

**Comment by rjmorris** [comment] 2015-08-01 17:59
I suspect this is a duplicate of #94.

**Comment by Caged** [comment] 2016-08-24 14:46
Triaging issues.  If this is still an issue could you please provide a working example?

**Closed by Caged** 2016-08-24 14:46 UTC
