### ISSUE TITLE
Tooltip withing same function does not update

### ISSUE THREAD

**Issue by vivekdtiwari** [Caged/d3-tip#130] opened 2015-09-22 11:42 UTC
I call the same function repeatedly applying new filters on data. Also each time I define a new tooltip. However this only works once. The content of the tooltip then gets fixed. Is there any way to clear the content and create new tooltip from scratch? .destroy() and d3.selectAll('.d3-tip').remove() do not help.

**Comment by Caged** [comment] 2016-08-24 15:02
Triaging Issues.  Closing as not a bug and underspecified.  Can you please provide a working example of your problem?

**Closed by Caged** 2016-08-24 15:02 UTC
