### ISSUE TITLE
Possible conflict with Google DefaultUI, DoubleClickZoom and scrollwheel

### ISSUE THREAD

**Issue by gigster99** [Caged/d3-tip#113] opened 2015-05-13 14:52 UTC
We have this initial d3.js [implementation](http://ontomatica.com/public/test/soils_Arizona/1_index.html), to which we would like to add `d3-tip` tool tips to reveal underlying data in a `.json` file. Here is the [first iteration](http://ontomatica.com/public/test/soils_Arizona/3_index.html) where
```
http://labratrevenge.com/d3-tip/javascripts/d3.tip.v0.6.3.js
```
appears to break the relationship between the circle overlay and its `lng-lat` coordinates. When using Google controls, the map is no longer synchronized with the overlay.

We need to use these settings:

1.  disableDefaultUI: true,
2.  disableDoubleClickZoom: true,
3.  scrollwheel: false

as [seen here](http://ontomatica.com/public/test/soils_Arizona/2_index.html).

If there is no systematic solution, we're OK with deprecating the Google controls as shown above, but a fix - or alternative approach - would be good.

May we also ask for your advice? Would you show us how to change:

```
var tip = d3.tip()
    .attr('class', 'd3-tip')
    .offset([+20, -20])
    .style({border: '1px solid #fff', 'border-radius': 'none'})
    .html(function(d) {
    console.log(JSON.stringify(d.value));
    return "<span>" + d.key + "</span><br>" + "chemical properties:<span>" + JSON.stringify(d.value) + "</span>";
    })
```

to look like the Google tool tip, seen when clicking, for example, "Ironwood Forest National Monument" located northwest of Tuscon. We'd like there to be only a small differences in the style of pop-up information from Google and from d3-tip using data from the `.json` file.

We would like the chemicals and their values to be a two column table [like this](https://github.com/JeffreyBLewis/congressional-district-boundaries/blob/master/Alabama_103_to_107.geojson).

On a second related matter, we would like to use d3-tip to present a URL on mouseover. Here is the [target example](http://ontomatica.com/public/test/soils_tree/1_index.html).

Here is the `.json` file - [similar to the one used above](http://ontomatica.com/public/test/soils_tree/1_index.json).

We've tried to introduce this d3-tip

```
var tip = d3.tip()
    .attr('class', 'd3-tip')
    .offset([+20, -20])
    .style({border: '1px solid #fff', 'border-radius': 'none'})
    .html(function(d) {
      console.log(JSON.stringify(d.value));
      return '<span>' + d.key + '</span><br>' + 'url:' + JSON.stringify(d.value) + '</span>';
    })
```

into this [JavaScript file](http://ontomatica.com/public/test/soils_tree/1_index.js), but cannot make it work.

We would like to use a URL string in this format:
```
"<a href=\"http://en.wikipedia.org/wiki/Albaqualfs\">Albaqualfs<\/a>"
```
to get a "clean" link in the tool-tip.

Thank you for your help on these items.

**Comment by Caged** [comment] 2015-05-14 15:27
There are 3 issues.  I'm not that familiar with google map controls, but addressing your first issue...

> When using Google controls, the map is no longer synchronized with the overlay.

This might be caused by the offset your using.  Have you tried removing it or setting it to `[0, 0]`? 

> .offset([+20, -20])

> May we also ask for your advice? Would you show us how to change:

You shouldn't need `JSON.stringify`, since you have an object.   To get the chemicals and values into a table, you could do something like in the `html` function.

``` javascript
var str = "<table><thead><tr><th>Chemical</th></tr></thead><tbody>"
var chems = Object.keys(d.value)
chems.forEach(function(chem) {
   str += "<tr><td>" + chem + "</td><td>" + d.value[chem] + "</td></tr>" 
})
str += '</tbody></table>'
return str
```

> We would like to use a URL string in this format:

You could return an HTML anchor in the `html` function:

``` javascript
.html(function(d) { return '<a href="' + d.url + '">' + d.name + '</a>' })
```

Also, you might be able to get more help for general issues like this on [StackOverflow](http://stackoverflow.com/).  I try to keep the issue tracker limited to bugs. 

Good luck!

**Comment by gigster99** [comment] 2015-05-14 15:33
TY - I will experiment now.

**Comment by Caged** [comment] 2016-08-24 15:01
Triaging issues.  Closing as not a bug.

**Closed by Caged** 2016-08-24 15:01 UTC
